// File generated by blabla

import isInvalidValue2 from '../isInvalidValue2';

describe('Module isInvalidValue2', () => {
  beforeEach(async () => {});

  it('Should work as expected', async () => {
    const a = 'REPLACE';
    const b = 'REPLACE';
    const c = 'REPLACE';
    const d = 'REPLACE';
    const e = 'REPLACE';
    const f = 'REPLACE';

    const result = await isInvalidValue2(a, b, { c, d }, e, f);
  });

  it('Error handling - should execute catch for try number 0', async () => {
    const a = 'REPLACE';
    const b = 'REPLACE';
    const c = 'REPLACE';
    const d = 'REPLACE';
    const e = 'REPLACE';
    const f = 'REPLACE';

    const result = await isInvalidValue2(a, b, { c, d }, e, f);
  });
});
